"""Removing image_name from post table

Revision ID: bd001696650c
Revises: 7cddb93ea398
Create Date: 2018-05-30 18:30:46.939797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd001696650c'
down_revision = '7cddb93ea398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
