"""Adding group to posts table

Revision ID: fcf06bcbde43
Revises: bd001696650c
Create Date: 2018-05-31 08:49:20.493105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf06bcbde43'
down_revision = 'bd001696650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'group')
    # ### end Alembic commands ###
